### ISSUE TITLE
valid html

### ISSUE THREAD

**Issue by tobiasgr** [dreyescat/bootstrap-rating#14]
Hi
Thank you for an awesome, and very simple rating plugin!
I tried validate my html after adding your plugin, but this setting:

<input type="hidden" class="rating" readonly="readonly"/>

is not valid html. input with type "hidden" does not have a readonly property.

**Comment by dreyescat** [comment]
Thanks @tobiasgr! I had no idea that `hidden` inputs cannot have `readonly` attributes. Nice you validated it.

I have created a *counterpart* `data-readonly` data attribute to replace the regular `readonly` one. By now both will be allowed but the regular `readonly` one will be deprecated in favor of the data version attribute.

So this version:

    <input type="hidden" class="rating" data-readonly>

should be used instead of:

    <input type="hidden" class="rating" readonly>

Now the [demo page was successfully checked as HTML5](https://validator.w3.org/check?uri=http%3A%2F%2Fdreyescat.github.io%2Fbootstrap-rating%2F&charset=%28detect+automatically%29&doctype=Inline&group=0&user-agent=W3C_Validator%2F1.3+http%3A%2F%2Fvalidator.w3.org%2Fservices)

For documentation:

According to the [W3C Markup Validation Service](https://validator.w3.org/) the `readonly` attribute is not allowed for hidden input elements.

> Attribute readonly not allowed on element input at this point.
>     `<input type="hidden" class="rating" readonly="readonly" value="3"/>`

It is only allowed for:

> Attribute readonly is only allowed when the input type is date, datetime, datetime-local, email, month, number, password, search, tel, text, time, url, or week.

**Comment by tobiasgr** [comment]
Awesome, that was fast! Thanks!
