### ISSUE TITLE
Readonly Problem

### ISSUE THREAD

**Issue by ReyzWB** [dreyescat/bootstrap-rating#6]
There's something wrong with my readonly rating. I have 5 stars rating with value 5, but rating icon is empty. For rating below 5, it works fine.

**Comment by dreyescat** [comment]
Thanks @ReyzWB for the catch! It should be fixed now.

It was a problem regarding the *old* way to define the ranges. In version 0.x the upper index wasn't included, so the default range was [0..5), and hence 5 was not included ```[0, 1, 2, 3, 4]```. Due to the addition of fractional symbols, I decided it was better to change ranges to (0..5], and hence having ```[1, 2, 3, 4, 5]```. But, as you found out, not everything was properly upgraded :).
